<?xml version="1.0"?>
<!--
  Copyright 2025-2026 University of Augsburg, Chair of Mechatronics by Noah Böckmann

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>lerobot_robot_ros</name>
  <version>0.1.0</version>
  <description>A lightweight ROS 2 wrapper for lerobot</description>
  <maintainer email="kontakt@noahb.de">Noah Böckmann</maintainer>
  <license>Apache-2.0</license>

  <depend>rclpy</depend>
  <depend>control_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>moveit_msgs</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>